---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: AWSMachineTemplate
metadata:
  annotations:
    cluster.x-k8s.io/conversion-data: '{"apiVersion":"infrastructure.cluster.x-k8s.io/v1beta1","kind":"AWSMachineTemplate","spec":{"template":{"metadata":{},"spec":{"ami":{},"cloudInit":{},"iamInstanceProfile":"nodes.cluster-api-provider-aws.sigs.k8s.io","imageLookupBaseOS":"centos-7","imageLookupFormat":"capa-ami-{{.BaseOS}}-?{{.K8sVersion}}-*","imageLookupOrg":"258751437250","instanceType":"m5.2xlarge","rootVolume":{"size":80},"sshKeyName":""}}}}'
  name: sbx-md-0
  namespace: default
spec:
  template:
    spec:
      ami: {}
      cloudInit: {}
      iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
      imageLookupBaseOS: centos-7
      imageLookupFormat: capa-ami-{{.BaseOS}}-?{{.K8sVersion}}-*
      imageLookupOrg: "258751437250"
      instanceType: m5.2xlarge
      rootVolume:
        size: 80
      sshKeyName: ""