---
apiVersion: cluster.x-k8s.io/v1alpha4
kind: Cluster
metadata:
  annotations:
    cluster.x-k8s.io/conversion-data: '{"apiVersion":"cluster.x-k8s.io/v1beta1","kind":"Cluster","spec":{"clusterNetwork":{"pods":{"cidrBlocks":["192.168.0.0/16"]},"services":{"cidrBlocks":["10.96.0.0/12"]}},"controlPlaneEndpoint":{"host":"","port":0},"controlPlaneRef":{"apiVersion":"controlplane.cluster.x-k8s.io/v1alpha4","kind":"KubeadmControlPlane","name":"sbx-control-plane","namespace":"default"},"infrastructureRef":{"apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha4","kind":"AWSCluster","name":"sbx","namespace":"default"}},"status":{"controlPlaneReady":false,"infrastructureReady":false}}'
  labels:
    konvoy.d2iq.io/autoscaler: cluster-api
    konvoy.d2iq.io/cluster-name: sbx
    konvoy.d2iq.io/cni: calico
    konvoy.d2iq.io/csi: aws-ebs
    konvoy.d2iq.io/provider: aws
  name: sbx
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneEndpoint:
    host: ""
    port: 0
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
    kind: KubeadmControlPlane
    name: sbx-control-plane
    namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
    kind: AWSCluster
    name: sbx
    namespace: default
status:
  infrastructureReady: false