---
apiVersion: v1
data:
  custom-resources.yaml: |
    # This section includes base Calico installation configuration.
    # For more information, see: https://docs.projectcalico.org/reference/installation/api
    apiVersion: operator.tigera.io/v1
    kind: Installation
    metadata:
      name: default
    spec:
      cni:
        type: Calico
      # Configures Calico networking.
      calicoNetwork:
        # Note: The ipPools section cannot be modified post-install.
        ipPools:
        - blockSize: 26
          cidr: 192.168.0.0/16
          encapsulation: IPIP
          natOutgoing: Enabled
          nodeSelector: all()
        bgp: Enabled
kind: ConfigMap
metadata:
  name: calico-cni-sbx
  namespace: default